apiVersion: v1
kind: ServiceAccount
metadata:
  name: __SERVICE_ACCOUNT__
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: __APP_NAME__-runtime
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: __APP_NAME__-runtime
subjects:
- kind: ServiceAccount
  name: __SERVICE_ACCOUNT__
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: __APP_NAME__-runtime
